---
- hosts: localhost
  vars:
    tomcat_port: 8885
  become: yes
  tasks:
    - name: Downloading Tomcat v8.5.54
      get_url:
        url:  http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
        dest: /usr/local
    - name: Extracting the downloaded file
      unarchive:
        src: /usr/local/apache-tomcat-8.5.54.tar.gz
        dest: /usr/local
    - name: Rename and copy to desried location
      command: mv /usr/local/apache-tomcat-8.5.54 /usr/local/tomcat
    - name: Change Tomcat port to custom port
      template:
        src: server.xml.j2
        dest: /usr/local/tomcat/conf/server.xml
    - name: Starting Tomcat
      shell: nohup /usr/local/tomcat/bin/startup.sh &
