---
- hosts: localhost
  vars:
    tomcat_port: 8885
  become: yes
  tasks:
    - name: downloading tomcat
      get_url:
        url:  http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.54/bin/apache-tomcat-8.5.54.tar.gz
        dest: /usr/local
    - name: extracting dwnloaded tomcat
      unarchive:
        src: /usr/local/apache-tomcat-8.5.54.tar.gz
        dest: /usr/local
    - name: move and copy
      command: mv /usr/local/apache-tomcat-8.5.54 /usr/local/tomcat
    - name: change to custom port
      template:
        src: server.xml.j2
        dest: /usr/local/tomcat/conf/server.xml
    - name: starting tomcat
      shell: nohup /usr/local/tomcat/bin/startup.sh &
